[package]
name = "ttywrite"
version = "0.1.0"
authors = ["Sergio Benitez <sb@sergio.bz>", "Rachel Rybarczyk <rj@rybar.tech"]
edition = "2018"

[dependencies]
structopt = "0.1.0"
structopt-derive = "0.1.0"
serial = "0.4"
xmodem = { path = "../xmodem" }
